//AUTHENTICATION
export const LOGIN_WITH_EMAIL_PASSWORD_SAGA = 'LOGIN_WITH_EMAIL_PASSWORD_SAGA';
export const FORGOT_PASSWORD_SAGA = 'FORGOT_PASSWORD_SAGA';

// PRODUCTS
export const GET_LIST_PRODUCTS_SAGA = 'GET_LIST_PRODUCTS_SAGA';
export const POST_PRODUCTS_SAGA = 'POST_PRODUCTS_SAGA';

// STAFF - USER
export const GET_LIST_USER_SAGA = 'GET_LIST_USER_SAGA';
export const POST_USER_SAGA = 'POST_USER_SAGA';
export const PUT_USER_SAGA = 'PUT_USER_SAGA';
export const DELETE_USER_SAGA = 'DELETE_USER_SAGA';

//DELIVERY NOTES
export const GET_LIST_DELIVERY_NOTES = 'GET_LIST_DELIVERY_NOTES';
export const POST_DELIVERY_NOTES = 'POST_DELIVERY_NOTES';
export const DELETE_DELIVERY_NOTES = 'DELETE_DELIVERY_NOTES';

//PROVIDERS
export const GET_LIST_PROVIDER = 'GET_LIST_PROVIDER';
export const POST_PROVIDER = 'POST_PROVIDER';
export const PUT_PROVIDER = 'PUT_PROVIDER';
export const DELETE_PROVIDER = 'DELETE_PROVIDER';