//AUTHENTICATION
export const LOGIN_WITH_EMAIL_PASSWORD_SAGA = 'LOGIN_WITH_EMAIL_PASSWORD_SAGA';
export const FORGOT_PASSWORD_SAGA = 'FORGOT_PASSWORD_SAGA';

// PRODUCTS
export const GET_LIST_PRODUCTS_SAGA = 'GET_LIST_PRODUCTS_SAGA';
export const POST_PRODUCTS_SAGA = 'POST_PRODUCTS_SAGA';
export const PUT_PRODUCTS_SAGA = 'PUT_PRODUCTS_SAGA';
export const DELETE_PRODUCTS_SAGA = 'DELETE_PRODUCTS_SAGA';
export const GET_PRODUCTS_BY_ID_SAGA = 'GET_PRODUCTS_BY_ID_SAGA';

// STAFF - USER
export const GET_LIST_USER_SAGA = 'GET_LIST_USER_SAGA';
export const POST_USER_SAGA = 'POST_USER_SAGA';
export const PUT_USER_SAGA = 'PUT_USER_SAGA';
export const DELETE_USER_SAGA = 'DELETE_USER_SAGA';
export const GET_USER_BY_ID_SAGA = 'GET_USER_BY_ID_SAGA';

//DELIVERY NOTES
export const GET_LIST_DELIVERY_NOTES_SAGA = 'GET_LIST_DELIVERY_NOTES_SAGA';
export const POST_DELIVERY_NOTES_SAGA = 'POST_DELIVERY_NOTES_SAGA';
export const DELETE_DELIVERY_NOTES_SAGA = 'DELETE_DELIVERY_NOTES_SAGA';
export const GET_DELIVERY_NOTES_ID_SAGA = 'GET_DELIVERY_NOTES_ID_SAGA';

//PROVIDERS
export const GET_LIST_PROVIDER_SAGA = 'GET_LIST_PROVIDER';
export const POST_PROVIDER_SAGA = 'POST_PROVIDER';
export const PUT_PROVIDER_SAGA = 'PUT_PROVIDER';
export const DELETE_PROVIDER_SAGA = 'DELETE_PROVIDER';
export const GET_PROVIDER_BY_ID_SAGA = 'GET_PROVIDER_BY_ID_SAGA';

// PRODUCT ITEM
export const POST_PRODUCT_ITEM_SAGA = 'POST_PRODUCTS_SAGA';
export const DELETE_PRODUCT_ITEM_SAGA = 'PUT_PRODUCTS_SAGA';